### ISSUE TITLE
Fennel in the Lazyman Neovim Configuration Manager

### ISSUE THREAD

**Issue by doctorfree** [jhchabran/nvim-config#2]
I've created a Neovim Configuration Manager that supports easy installation and initialization of multiple Neovim configurations using the `NVIM_APPNAME` environment variable in Neovim 0.9.  I call it Lazyman and include support for your `nvim-config` repository (called `Fennel` in Lazyman) as one of the "Personal" Neovim configurations installed and initialized by `lazyman`.

See https://github.com/doctorfree/nvim-lazyman for info on Lazyman.

I'm contacting the maintainers of the Lazyman supported Neovim configurations to seek any feedback on the description, installation, and initialization of their config in Lazyman. Please feel free to let me know what I'm doing wrong or how I could improve the incorporation of `Fennel` in Lazyman. If you feel there is a need to modify the way `Fennel` is used in Lazyman then open an issue at https://github.com/doctorfree/nvim-lazyman/issues

This isn't really an issue with `nvim-config`, it is just a heads up and request for feedback.

Your Fennel based Neovim config is very cool. Thanks!

**Comment by jhchabran** [comment]
Hello @doctorfree! Sorry for answering so late, classic case of a github notification landing when you're busy annnnnd you forget about it. 

I'm happy to see that someone finds my config cool 😊 

I think the main issue with my config, is that quite frankly, I'm not sure that it works out of the box when cloned. As an example or a starting point, I think it might be useful, but I think that a few things might break right now if starting fresh.

**Comment by doctorfree** [comment]
Hi @jhchabran 

It works for me when installed with `lazyman`. I don't do any patching, it's just cloned and initialized with Packer. Perhaps there are some features that do not work properly but I just have not hit them yet in my testing. If you have any suggestions for further testing I would welcome them.

Your config is a valuable learning resource, especially since it is written in Fennel. Another Lazyman supported config is written in C. These are, in my opinion, excellent resources for those wishing to explore and learn. Thanks!
